---

defaults:
  - _self_
  - model: basic # by default `model` will point to the content in `conf/model/basic.yaml`
  # if you'd like to it to point to the resnet.yaml file instead, run the code as: python client.py model=resnet
  - location: B

wait_for_server: 0 # wait for this many seconds before starting the client
client:
  _target_: client.FlowerClient
  _recursive_: false # tell Hydra not to instantiate child nodes (for instance to give us control when the model object is instantiated)
  local_epochs: 1
  net_config: ${model} # a refenence to the model node in the config
  device: cpu # or cuda:0
  location: ${location}

hydra:
  run:
    dir: ./outputs/client/${location.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}