name: Build docker SuperLink image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower."
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-superlink-images:
    name: Build images
    uses: ./.github/workflows/_docker-build.yml
    # run only on default branch when using it with workflow_dispatch
    if: github.ref_name == github.event.repository.default_branch
    with:
      namespace-repository: flwr/superlink
      file-dir: src/docker/superlink
      build-args: |
        FLWR_VERSION=${{ github.event.inputs.flwr-version }}
        PYTHON_VERSION=3.11
        UBUNTU_VERSION=ubuntu22.04
      tags: |
        ${{ github.event.inputs.flwr-version }}-py3.11-ubuntu22.04
        ${{ github.event.inputs.flwr-version }}
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  summary:
    name: Summary
    runs-on: ubuntu-22.04
    needs: build-superlink-images
    timeout-minutes: 10
    steps:
      - run: |
          echo "### Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for IMAGE in $(echo ${{ toJson(needs.build-superlink-images.outputs.metadata) }} | jq -r '.tags[]' ); do
            echo "- $IMAGE" >> $GITHUB_STEP_SUMMARY
          done
